## Python Libraries - Pandas - Merge and Append

In this section, you will merge and concatenate multiple dataframes. Merging is one of the most common operations you will do, since data often comes in various files.

### Merging

For merging, we have sales data across multiple sheets in an Excel file. We will now work with all these sheets and learn to:
* Merge multiple dataframes using common columns/keys using ```pd.merge()```

Let's first read all the data files.

In [1]:
# import the required libraries
import numpy as np
import pandas as pd

In [23]:
# read the sheets from file 'sales_returns.xlsx' into 2 different dataframes - orders and returns
orders =  pd.read_excel("sales_returns.xlsx",sheet_name = "Orders")
returns = pd.read_excel("sales_returns.xlsx",sheet_name = "Returns")

In [24]:
# Check the shape of the dataframe 'orders'
orders.shape

(25728, 4)

In [25]:
# Check the shape of the dataframe 'returns'
returns.shape

(1079, 2)

In [26]:
# check the dataframe 'orders' and 'returns'
orders.head()
# returns.head()

               Order ID  Market  Profit   Sales
0  AG-2012-AA6453-41020  Africa   53.76  298.68
1  AG-2012-AC4203-40915  Africa   14.58   91.38
2  AG-2012-AH2103-41133  Africa   11.04  276.96
3  AG-2012-AJ7803-40978  Africa    7.17   35.97
4  AG-2012-AS2853-41235  Africa   15.36   54.90

In [27]:
# Create a dataframe 'return_orders' by merging the two dataframes on Order_ID
return_orders = orders.merge(returns , on = "Order ID")

# Check the created dataframe
return_orders

                      Order ID  Market    Profit     Sales Returned
0        AG-2013-PO88653-41634  Africa  191.2500  1932.240      Yes
1        AG-2014-CM21603-41755  Africa   10.3200    43.050      Yes
2        AG-2014-CP20853-41889  Africa   14.1000    84.720      Yes
3        AG-2014-RD95853-41712  Africa   21.0300    64.380      Yes
4        AO-2013-JE57454-41544  Africa  106.5900   499.230      Yes
5       AO-2013-SF102004-41628  Africa   83.5200   298.620      Yes
6       BN-2012-RW963015-41216  Africa  247.4400   546.000      Yes
7       BN-2014-KB631515-41904  Africa    2.7300    30.480      Yes
8       CG-2012-MM828033-40983  Africa  112.6200   225.240      Yes
9      CG-2013-SC1030533-41538  Africa  245.3700  1945.890      Yes
10      CG-2014-ML775533-41740  Africa   37.6800   193.440      Yes
11       CG-2015-AM70533-42233  Africa   90.1200   391.860      Yes
12      CG-2015-DW358533-42341  Africa   30.1500    79.380      Yes
13      CG-2015-PV898533-42225  Africa   17.7600   197.490      Yes
14     CM-2012-SC1068022-41009  Africa    8.5200    56.820      Yes
15      EG-2012-MC727538-41130  Africa   28.9200   137.790      Yes
16      EG-2012-NM844538-41002  Africa   10.6800    44.130      Yes
17      EG-2013-FA423038-41534  Africa    3.6000    45.000      Yes
18     EG-2013-VG1179038-41590  Africa    2.5200    64.080      Yes
19      EG-2014-CS186038-41690  Africa    1.5000    18.990      Yes
20      EG-2014-PM894038-41846  Africa    9.0300    25.830      Yes
21     EG-2014-SB1018538-41944  Africa   14.7900    51.090      Yes
22     EG-2014-SC1009538-41847  Africa  103.7100   438.930      Yes
23       EG-2015-AC66038-42250  Africa  377.4300  1421.130      Yes
24       EG-2015-AY55538-42121  Africa    2.5200   256.860      Yes
25      EG-2015-CM211538-42144  Africa  145.0200  1297.950      Yes
26      EG-2015-DM301538-42367  Africa   21.6900   636.660      Yes
27      EG-2015-NF838538-42060  Africa    3.7800    31.560      Yes
28      EG-2015-RA994538-42342  Africa   68.7600   273.090      Yes
29      EG-2015-RM937538-42360  Africa   22.8000    58.200      Yes
...                        ...     ...       ...       ...      ...
1049  US-2012-TH21235140-41216    USCA    0.7938     2.940      Yes
1050  US-2013-DG13300140-41458    USCA   29.5324   458.072      Yes
1051  US-2013-DR12940140-41635    USCA   -3.1680    12.672      Yes
1052  US-2013-HG14845140-41530    USCA   -2.0100     2.412      Yes
1053  US-2013-KB16315140-41318    USCA  -92.8368   427.548      Yes
1054  US-2013-ON18715140-41411    USCA  -44.9892    47.368      Yes
1055  US-2013-RR19525140-41613    USCA   10.9602    97.424      Yes
1056  US-2014-BG11695140-42001    USCA  -12.0784   845.488      Yes
1057  US-2014-DR12880140-41723    USCA   25.1980   403.168      Yes
1058  US-2014-FO14305140-41944    USCA   11.2224    32.064      Yes
1059  US-2014-GT14710140-41980    USCA  297.4051  1169.454      Yes
1060  US-2014-KD16495140-41976    USCA   75.6516   203.108      Yes
1061  US-2014-LB16795140-41957    USCA   -4.7040     3.136      Yes
1062  US-2014-PK19075140-41907    USCA  -13.3176   155.372      Yes
1063  US-2014-RB19570140-41886    USCA    0.0000   198.744      Yes
1064  US-2014-SC20230140-41873    USCA  275.9000  3339.122      Yes
1065  US-2014-SP20860140-41968    USCA  618.7338  2904.572      Yes
1066  US-2014-VM21835140-41772    USCA   49.1409   128.670      Yes
1067  US-2015-CR12820140-42284    USCA  133.2009   681.910      Yes
1068  US-2015-DH13075140-42092    USCA  106.9836  1435.960      Yes
1069  US-2015-EB13930140-42208    USCA  -75.1920   526.344      Yes
1070  US-2015-GZ14470140-42362    USCA    5.9312    13.480      Yes
1071  US-2015-GZ14545140-42212    USCA  705.2740  2012.302      Yes
1072  US-2015-JE15610140-42321    USCA    4.9056    14.016      Yes
1073  US-2015-LH16900140-42348    USCA   48.5514   143.856      Yes
1074  US-2015-ME17320140-42322    USCA  -24.7086     9.324      Yes
1075  US-2015-PN18775140-42339    USCA    8.9970    71.976      Yes
1076  US-2015-RL19615140-42147    USCA   18.8328    49.560      Yes
1077  US-2015-SC20050140-42278    USCA  -17.4690    11.646      Yes
1078  US-2015-TT21220140-42186    USCA  100.4255   204.950      Yes

[1079 rows x 5 columns]

In [28]:
# Check the shape of the new dataframe
return_orders.shape

(1079, 5)

In [29]:
# try to use the 'left' method to join two dataframes

return_orders = orders.merge(returns , on = "Order ID" , how = "left")
# Check the created dataframe
return_orders

                       Order ID  Market     Profit     Sales Returned
0          AG-2012-AA6453-41020  Africa    53.7600   298.680      NaN
1          AG-2012-AC4203-40915  Africa    14.5800    91.380      NaN
2          AG-2012-AH2103-41133  Africa    11.0400   276.960      NaN
3          AG-2012-AJ7803-40978  Africa     7.1700    35.970      NaN
4          AG-2012-AS2853-41235  Africa    15.3600    54.900      NaN
5         AG-2012-BC11253-41219  Africa     4.1400    10.920      NaN
6         AG-2012-BM17853-41052  Africa   148.6800   874.680      NaN
7         AG-2012-BM17853-41085  Africa   177.1800   510.240      NaN
8         AG-2012-CC23703-40970  Africa    29.4300   113.280      NaN
9         AG-2012-DB32103-41257  Africa    20.5200    58.740      NaN
10        AG-2012-DH36753-41136  Africa   222.4800   607.260      NaN
11        AG-2012-DK28353-41264  Africa   349.5600  1589.400      NaN
12        AG-2012-EG39003-41262  Africa    86.7900  1475.970      NaN
13        AG-2012-JH59853-41214  Africa    10.8600    24.720      NaN
14        AG-2012-MW82203-41108  Africa    19.3200    55.440      NaN
15        AG-2012-MW82203-41268  Africa    27.8400   116.040      NaN
16        AG-2012-OT87303-41262  Africa    29.7000   198.090      NaN
17        AG-2012-RO97803-40964  Africa   331.7100  1408.410      NaN
18        AG-2012-RS97653-41074  Africa     4.0800    11.370      NaN
19       AG-2012-TB112803-40909  Africa   106.1400   408.300      NaN
20       AG-2012-TH112353-40918  Africa    61.7100   308.640      NaN
21       AG-2012-TT110703-41133  Africa     4.2600    10.410      NaN
22         AG-2013-AA4803-41494  Africa     8.7900   110.100      NaN
23        AG-2013-BP12303-41486  Africa    96.5700   362.700      NaN
24        AG-2013-CC24303-41517  Africa    61.1700   153.240      NaN
25        AG-2013-CP23403-41422  Africa   632.7900  2366.100      NaN
26        AG-2013-DC32853-41506  Africa    98.8500   269.490      NaN
27        AG-2013-GH44103-41604  Africa     3.1500    16.710      NaN
28        AG-2013-KF62853-41594  Africa    23.7900   105.360      NaN
29        AG-2013-LC70503-41535  Africa   210.5400   754.710      NaN
...                         ...     ...        ...       ...      ...
25698  US-2015-SW20245140-42061    USCA   -16.3402   428.704      NaN
25699  US-2015-SW20350140-42207    USCA   -50.2500   466.814      NaN
25700  US-2015-SZ20035140-42189    USCA   -81.6628   279.004      NaN
25701  US-2015-TB21250140-42020    USCA   -31.3862   147.636      NaN
25702  US-2015-TB21400140-42094    USCA    20.6063   170.872      NaN
25703  US-2015-TB21625140-42326    USCA    20.5860    43.800      NaN
25704  US-2015-TB21625140-42339    USCA   -15.4188  1079.316      NaN
25705  US-2015-TC21295140-42322    USCA     0.1548     2.064      NaN
25706  US-2015-TC21475140-42125    USCA   -69.3952    43.372      NaN
25707  US-2015-TD20995140-42195    USCA    -0.7920     1.080      NaN
25708  US-2015-TG21310140-42032    USCA    35.8644   137.940      NaN
25709  US-2015-TH21235140-42153    USCA   -35.2443   110.433      NaN
25710  US-2015-TH21550140-42297    USCA -1306.5504  1633.188      NaN
25711  US-2015-TN21040140-42279    USCA    21.9975   104.750      NaN
25712  US-2015-TP21130140-42343    USCA   176.5220   551.550      NaN
25713  US-2015-TP21565140-42019    USCA    -0.0385   337.688      NaN
25714  US-2015-TS21085140-42012    USCA    -1.9656     2.808      NaN
25715  US-2015-TS21370140-42136    USCA  -356.9643   209.979      NaN
25716  US-2015-TS21610140-42314    USCA    28.6682   246.380      NaN
25717  US-2015-TT21220140-42186    USCA   100.4255   204.950      Yes
25718  US-2015-TT21460140-42068    USCA   -76.1086   114.684      NaN
25719  US-2015-TT21460140-42237    USCA     3.5960    35.960      NaN
25720  US-2015-TW21025140-42207    USCA     3.1752     6.480      NaN
25721  US-2015-VG21790140-42215    USCA    25.5112   115.960      NaN
25722  US-2015-VM21685140-42080    USCA    54.4690   712.966      NaN
25723  US-2015-VM21835140-42252    USCA     6.9654    14.820      NaN
25724  US-2015-WB21850140-42349    USCA    12.8767    91.193      NaN
25725  US-2015-XP21865140-42287    USCA    16.5440    35.200      NaN
25726  US-2015-XP21865140-42323    USCA   -22.7882   212.992      NaN
25727  US-2015-ZC21910140-42175    USCA    41.1900   148.884      NaN

[25728 rows x 5 columns]

In [30]:
# Check the orders where orders were returned
return_orders[return_orders["Returned"]== "Yes"]

                       Order ID  Market    Profit     Sales Returned
35        AG-2013-PO88653-41634  Africa  191.2500  1932.240      Yes
44        AG-2014-CM21603-41755  Africa   10.3200    43.050      Yes
45        AG-2014-CP20853-41889  Africa   14.1000    84.720      Yes
56        AG-2014-RD95853-41712  Africa   21.0300    64.380      Yes
111       AO-2013-JE57454-41544  Africa  106.5900   499.230      Yes
116      AO-2013-SF102004-41628  Africa   83.5200   298.620      Yes
158      BN-2012-RW963015-41216  Africa  247.4400   546.000      Yes
165      BN-2014-KB631515-41904  Africa    2.7300    30.480      Yes
210      CG-2012-MM828033-40983  Africa  112.6200   225.240      Yes
251     CG-2013-SC1030533-41538  Africa  245.3700  1945.890      Yes
292      CG-2014-ML775533-41740  Africa   37.6800   193.440      Yes
314       CG-2015-AM70533-42233  Africa   90.1200   391.860      Yes
332      CG-2015-DW358533-42341  Africa   30.1500    79.380      Yes
363      CG-2015-PV898533-42225  Africa   17.7600   197.490      Yes
386     CM-2012-SC1068022-41009  Africa    8.5200    56.820      Yes
473      EG-2012-MC727538-41130  Africa   28.9200   137.790      Yes
476      EG-2012-NM844538-41002  Africa   10.6800    44.130      Yes
505      EG-2013-FA423038-41534  Africa    3.6000    45.000      Yes
533     EG-2013-VG1179038-41590  Africa    2.5200    64.080      Yes
547      EG-2014-CS186038-41690  Africa    1.5000    18.990      Yes
587      EG-2014-PM894038-41846  Africa    9.0300    25.830      Yes
596     EG-2014-SB1018538-41944  Africa   14.7900    51.090      Yes
597     EG-2014-SC1009538-41847  Africa  103.7100   438.930      Yes
607       EG-2015-AC66038-42250  Africa  377.4300  1421.130      Yes
611       EG-2015-AY55538-42121  Africa    2.5200   256.860      Yes
620      EG-2015-CM211538-42144  Africa  145.0200  1297.950      Yes
633      EG-2015-DM301538-42367  Africa   21.6900   636.660      Yes
669      EG-2015-NF838538-42060  Africa    3.7800    31.560      Yes
676      EG-2015-RA994538-42342  Africa   68.7600   273.090      Yes
681      EG-2015-RM937538-42360  Africa   22.8000    58.200      Yes
...                         ...     ...       ...       ...      ...
25073  US-2012-TH21235140-41216    USCA    0.7938     2.940      Yes
25098  US-2013-DG13300140-41458    USCA   29.5324   458.072      Yes
25102  US-2013-DR12940140-41635    USCA   -3.1680    12.672      Yes
25116  US-2013-HG14845140-41530    USCA   -2.0100     2.412      Yes
25142  US-2013-KB16315140-41318    USCA  -92.8368   427.548      Yes
25187  US-2013-ON18715140-41411    USCA  -44.9892    47.368      Yes
25203  US-2013-RR19525140-41613    USCA   10.9602    97.424      Yes
25237  US-2014-BG11695140-42001    USCA  -12.0784   845.488      Yes
25277  US-2014-DR12880140-41723    USCA   25.1980   403.168      Yes
25298  US-2014-FO14305140-41944    USCA   11.2224    32.064      Yes
25304  US-2014-GT14710140-41980    USCA  297.4051  1169.454      Yes
25329  US-2014-KD16495140-41976    USCA   75.6516   203.108      Yes
25336  US-2014-LB16795140-41957    USCA   -4.7040     3.136      Yes
25377  US-2014-PK19075140-41907    USCA  -13.3176   155.372      Yes
25388  US-2014-RB19570140-41886    USCA    0.0000   198.744      Yes
25401  US-2014-SC20230140-41873    USCA  275.9000  3339.122      Yes
25416  US-2014-SP20860140-41968    USCA  618.7338  2904.572      Yes
25433  US-2014-VM21835140-41772    USCA   49.1409   128.670      Yes
25494  US-2015-CR12820140-42284    USCA  133.2009   681.910      Yes
25509  US-2015-DH13075140-42092    USCA  106.9836  1435.960      Yes
25529  US-2015-EB13930140-42208    USCA  -75.1920   526.344      Yes
25555  US-2015-GZ14470140-42362    USCA    5.9312    13.480      Yes
25556  US-2015-GZ14545140-42212    USCA  705.2740  2012.302      Yes
25568  US-2015-JE15610140-42321    USCA    4.9056    14.016      Yes
25613  US-2015-LH16900140-42348    USCA   48.5514   143.856      Yes
25622  US-2015-ME17320140-42322    USCA  -24.7086     9.324      Yes
25659  US-2015-PN18775140-42339    USCA    8.9970    71.976      Yes
25675  US-2015-RL19615140-42147    USCA   18.8328    49.560      Yes
25685  US-2015-SC20050140-42278    USCA  -17.4690    11.646      Yes
25717  US-2015-TT21220140-42186    USCA  100.4255   204.950      Yes

[1079 rows x 5 columns]

In [31]:
# Print the dataframe summary using the info() command
return_orders.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25728 entries, 0 to 25727
Data columns (total 5 columns):
Order ID    25728 non-null object
Market      25728 non-null object
Profit      25728 non-null float64
Sales       25728 non-null float64
Returned    1079 non-null object
dtypes: float64(2), object(3)
memory usage: 1.2+ MB

In [32]:
# Change the data type of the column 'Returned' 

return_orders["Returned"] = return_orders["Returned"].astype("str")
# Check the dataframe after modification
return_orders.head()

               Order ID  Market  Profit   Sales Returned
0  AG-2012-AA6453-41020  Africa   53.76  298.68      nan
1  AG-2012-AC4203-40915  Africa   14.58   91.38      nan
2  AG-2012-AH2103-41133  Africa   11.04  276.96      nan
3  AG-2012-AJ7803-40978  Africa    7.17   35.97      nan
4  AG-2012-AS2853-41235  Africa   15.36   54.90      nan

In [33]:
# Replace the 'nan' value with 'No' in the column 'Returned'
return_orders["Returned"] = return_orders["Returned"].apply(lambda x : "No" if x == "nan"else "Yes")

# Check the dataframe after modification
return_orders

                       Order ID  Market     Profit     Sales Returned
0          AG-2012-AA6453-41020  Africa    53.7600   298.680       No
1          AG-2012-AC4203-40915  Africa    14.5800    91.380       No
2          AG-2012-AH2103-41133  Africa    11.0400   276.960       No
3          AG-2012-AJ7803-40978  Africa     7.1700    35.970       No
4          AG-2012-AS2853-41235  Africa    15.3600    54.900       No
5         AG-2012-BC11253-41219  Africa     4.1400    10.920       No
6         AG-2012-BM17853-41052  Africa   148.6800   874.680       No
7         AG-2012-BM17853-41085  Africa   177.1800   510.240       No
8         AG-2012-CC23703-40970  Africa    29.4300   113.280       No
9         AG-2012-DB32103-41257  Africa    20.5200    58.740       No
10        AG-2012-DH36753-41136  Africa   222.4800   607.260       No
11        AG-2012-DK28353-41264  Africa   349.5600  1589.400       No
12        AG-2012-EG39003-41262  Africa    86.7900  1475.970       No
13        AG-2012-JH59853-41214  Africa    10.8600    24.720       No
14        AG-2012-MW82203-41108  Africa    19.3200    55.440       No
15        AG-2012-MW82203-41268  Africa    27.8400   116.040       No
16        AG-2012-OT87303-41262  Africa    29.7000   198.090       No
17        AG-2012-RO97803-40964  Africa   331.7100  1408.410       No
18        AG-2012-RS97653-41074  Africa     4.0800    11.370       No
19       AG-2012-TB112803-40909  Africa   106.1400   408.300       No
20       AG-2012-TH112353-40918  Africa    61.7100   308.640       No
21       AG-2012-TT110703-41133  Africa     4.2600    10.410       No
22         AG-2013-AA4803-41494  Africa     8.7900   110.100       No
23        AG-2013-BP12303-41486  Africa    96.5700   362.700       No
24        AG-2013-CC24303-41517  Africa    61.1700   153.240       No
25        AG-2013-CP23403-41422  Africa   632.7900  2366.100       No
26        AG-2013-DC32853-41506  Africa    98.8500   269.490       No
27        AG-2013-GH44103-41604  Africa     3.1500    16.710       No
28        AG-2013-KF62853-41594  Africa    23.7900   105.360       No
29        AG-2013-LC70503-41535  Africa   210.5400   754.710       No
...                         ...     ...        ...       ...      ...
25698  US-2015-SW20245140-42061    USCA   -16.3402   428.704       No
25699  US-2015-SW20350140-42207    USCA   -50.2500   466.814       No
25700  US-2015-SZ20035140-42189    USCA   -81.6628   279.004       No
25701  US-2015-TB21250140-42020    USCA   -31.3862   147.636       No
25702  US-2015-TB21400140-42094    USCA    20.6063   170.872       No
25703  US-2015-TB21625140-42326    USCA    20.5860    43.800       No
25704  US-2015-TB21625140-42339    USCA   -15.4188  1079.316       No
25705  US-2015-TC21295140-42322    USCA     0.1548     2.064       No
25706  US-2015-TC21475140-42125    USCA   -69.3952    43.372       No
25707  US-2015-TD20995140-42195    USCA    -0.7920     1.080       No
25708  US-2015-TG21310140-42032    USCA    35.8644   137.940       No
25709  US-2015-TH21235140-42153    USCA   -35.2443   110.433       No
25710  US-2015-TH21550140-42297    USCA -1306.5504  1633.188       No
25711  US-2015-TN21040140-42279    USCA    21.9975   104.750       No
25712  US-2015-TP21130140-42343    USCA   176.5220   551.550       No
25713  US-2015-TP21565140-42019    USCA    -0.0385   337.688       No
25714  US-2015-TS21085140-42012    USCA    -1.9656     2.808       No
25715  US-2015-TS21370140-42136    USCA  -356.9643   209.979       No
25716  US-2015-TS21610140-42314    USCA    28.6682   246.380       No
25717  US-2015-TT21220140-42186    USCA   100.4255   204.950      Yes
25718  US-2015-TT21460140-42068    USCA   -76.1086   114.684       No
25719  US-2015-TT21460140-42237    USCA     3.5960    35.960       No
25720  US-2015-TW21025140-42207    USCA     3.1752     6.480       No
25721  US-2015-VG21790140-42215    USCA    25.5112   115.960       No
25722  US-2015-VM21685140-42080    USCA    54.4690   712.966       No
25723  US-2015-VM21835140-42252    USCA     6.9654    14.820       No
25724  US-2015-WB21850140-42349    USCA    12.8767    91.193       No
25725  US-2015-XP21865140-42287    USCA    16.5440    35.200       No
25726  US-2015-XP21865140-42323    USCA   -22.7882   212.992       No
25727  US-2015-ZC21910140-42175    USCA    41.1900   148.884       No

[25728 rows x 5 columns]

### Append / Concatenate

Concatenation is much more straightforward than merging. It is used when you have dataframes having the same columns and want to append them (pile one on top of the other), or having the same rows and want to append them side-by-side.

In [ ]:
# Import the required libraries

**Appending rows in a dataframe**

In [34]:
# Dataframes having the same columns

df1 = pd.DataFrame({'Name': ['Aman', 'Joy', 'Rashmi', 'Saif'],
                    'Age' : ['34', '31', '22', '33'], 
                    'Gender': ['M', 'M', 'F', 'M']}
                  )

df2 = pd.DataFrame({'Name': ['Akhil', 'Asha', 'Preeti'],
                    'Age' : ['31', '22', '23'], 
                    'Gender': ['M', 'F', 'F']}
                  )

In [36]:
# Append the rows of df2 in df1
df1.append(df2)

     Name Age Gender
0    Aman  34      M
1     Joy  31      M
2  Rashmi  22      F
3    Saif  33      M
0   Akhil  31      M
1    Asha  22      F
2  Preeti  23      F

**Appending columns in a dataframe**

In [37]:
# Another dataframe with same number of rows as df1
df3 = pd.DataFrame({'School': ['RK Public', 'JSP', 'Carmel Convent', 'St. Paul'],
                    'Graduation Marks': ['84', '89', '76', '91']}
                  )

In [38]:
# Concatenating the dataframes: df1 and df3
pd.concat([df1 , df3])

C:\Users\Sanjeev\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

   Age Gender Graduation Marks    Name          School
0   34      M              NaN    Aman             NaN
1   31      M              NaN     Joy             NaN
2   22      F              NaN  Rashmi             NaN
3   33      M              NaN    Saif             NaN
0  NaN    NaN               84     NaN       RK Public
1  NaN    NaN               89     NaN             JSP
2  NaN    NaN               76     NaN  Carmel Convent
3  NaN    NaN               91     NaN        St. Paul

In [39]:
# Concatenating the dataframes across column: df1 and df3
pd.concat([df1 , df3] , axis = 1)

     Name Age Gender          School Graduation Marks
0    Aman  34      M       RK Public               84
1     Joy  31      M             JSP               89
2  Rashmi  22      F  Carmel Convent               76
3    Saif  33      M        St. Paul               91